### ISSUE TITLE
Profile model (BE)

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-latte#47]
Profile has a description, location, entrepreneur details (startup name, description, team, market size, traction, goals, investment goal in exchange for equity amount etc.) investor details (what types of startups I like, average cheque size, my expertise/ work experience etc.)

**Comment by danielbrog** [comment]
@aeciorc it looks like a lot of the entrepreneur details are something more in line with each project details (startup name, description,team, marketsize, investment goal) is there something I'm misunderstanding with the profile?

**Comment by aeciorc** [comment]
That's true, @danielbrog. Skip those, let's not add details that are specific to projects
